### ISSUE TITLE
Problema  a validação na Entidade

### ISSUE THREAD

**Issue by CesaragsUC** [Rickedb/DomainValidationCore#1]
Beleza? obrigado por essa versão pro NETCore, estou tendo problema quando tento validar se email já existe por exemplo.
 essa é minha classe que faz validação: http://prntscr.com/o1kglz
Essa minha entidade onde tento aplicar : http://prntscr.com/o1kh79

parece que ele pede rpa fazer injeção da minha interface, mas na versão do eduardo pires isso não é necessário?

**Comment by Rickedb** [comment]
Olá Cesar,

Isso acontece porque você precisa da sua service (que provavelmente acessa o banco).

Neste caso como vc inclui ele no seu validador/especificação, vc necessita incluir uma instância da sua interface no construtor.
Ou de alguma forma usar injeção de dependência para isso.

Certamente se você fizer igual na versão .net Framework do Eduardo Pires vc obterá o mesmo erro.
