### ISSUE TITLE
Support for .net core 3.0 and .net standard 2.1

### ISSUE THREAD

**Issue by InfantIvan** [Rickedb/DomainValidationCore#2]
Any plans to upgrade the package to support for .net core 3.0 and .net standard 2.1.

Kindly advise

**Comment by Rickedb** [comment]
Hello!
Sure! I'll be providing it until the end of the week!

**Comment by Rickedb** [comment]
done:
[Version 1.1.1 deployed to .net core 3.X](https://www.nuget.org/packages/DomainValidationCore/1.1.1)
